### ISSUE TITLE
PEのテスト用のやつです

### ISSUE THREAD

**Issue by mamezou10** [yyoshiaki/auto_counttable_maker#11]
[experimentMatrix_test_miceAPC.xlsx](https://github.com/yyoshiaki/auto_counttable_maker/files/2867340/experimentMatrix_test_miceAPC.xlsx)

なぜかcsvが挿入できず、エクセル形式です
WTとTGのマウスをn=3で比較してます
https://www.ncbi.nlm.nih.gov/bioproject?LinkName=sra_bioproject&from_uid=5935763

**Comment by yyoshiaki** [comment]
@mamezou10 
https://github.com/yyoshiaki/auto_counttable_maker/commit/a13ca46849044e9aca8dbdb6dd44a9b3ddd626fe

反映しました。READMEも書き換えてあります。
