### ISSUE TITLE
-t 4 or --thread 4が通らない

### ISSUE THREAD

**Issue by yyoshiaki** [yyoshiaki/auto_counttable_maker#25]
タイトルのとおりです。あとは大丈夫そう。

**Comment by yyoshiaki** [comment]
-u, --udockerもとおらない

**Comment by yyoshiaki** [comment]
udockerは解決。

**Comment by YusukeKawasaki** [comment]
了解です
テストしたいので入力全体教えていただいても良いですか？

**Comment by yyoshiaki** [comment]
ありがとう！

```
cd test/Illumina_PE && bash ../../MakeCountTable_Illumina_trimgalore_SRR.sh Illumina_PE_SRR.csv mouse --threads 8
```

**Comment by YusukeKawasaki** [comment]
僕の環境でTHREADS=8が代入されるところまでは確認出来たのですが、それ以降の問題でしょうか…？
それともオプションバース中に止まりますか？

**Comment by yyoshiaki** [comment]
パース中に止まる！

![image](https://user-images.githubusercontent.com/19543497/54178434-1e646a00-44d9-11e9-83b6-82c9756aa8d7.png)

**Comment by YusukeKawasaki** [comment]
68行目の$EX_MATRIX_FILEを$1に置き換えてください

**Comment by yyoshiaki** [comment]
ごめん、僕がreplaceしてました。。。
