### ISSUE TITLE
MakeCountTable_Illumina_trimgalore_SRR.sh: line 219: IF_TEST: unbound variableと出てしまう

### ISSUE THREAD

**Issue by ykohki** [yyoshiaki/auto_counttable_maker#26]
`$ bash MakeCountTable_Illumina_trimgalore_SRR.sh SRP043671.csv mouse`
で実行すると、スクリプト219行のところでIF_TESTが定義されていないと出ます。
SRP043671.csvは下の画像のものです。
![image](https://user-images.githubusercontent.com/43834721/54653176-16ba4c00-4afd-11e9-8b09-23fdc4136020.png)

**Comment by yyoshiaki** [comment]
https://github.com/yyoshiaki/auto_counttable_maker/blob/master/MakeCountTable_Illumina_trimgalore_SRR.sh#L50

ちょっと足してみました。どうでしょうか。

**Comment by ykohki** [comment]
ありがとうございます！
ひとまずこの部分はいけてそうです。
![image](https://user-images.githubusercontent.com/43834721/54660025-d5836580-4b17-11e9-9490-9d400b95c247.png)

**Comment by yyoshiaki** [comment]
よかった！
