### ISSUE TITLE
fasterq-dumpでとまります

### ISSUE THREAD

**Issue by mamezou10** [yyoshiaki/auto_counttable_maker#27]
SRRのダウンロードが途中でとまってしまうようになりました。。
全部で９個のうち３個めでエラーとなり、ディレクトリの問題かと別のHDDで試してみたら１個めから止まってしまう始末です。。
サーバーダウンしてるかもしれないしネット接続の問題かもしれないのですが、一応共有します
fasterq-dump.2.9.2 sys: timeout exhausted while reading file within network system module - mbedtls_ssl_read returned -76 ( NET - Reading information from the socket failed )

**Comment by yyoshiaki** [comment]
プログラムは動き続けていますか？私もたまにその警告が出ますが、放置していたら問題なく終わることが多いです。いかがでしょうか？

**Comment by yyoshiaki** [comment]
https://github.com/ncbi/sra-tools/issues/137
いや、止まってるなら普通にfirewallの問題かも。

**Comment by mamezou10** [comment]
なるほど！一昨日のものは止まってしまいました
今走らせてるのはまだ頑張っているみたいなので、様子見てまたご報告します
Firewallも確認してみます！ありがとうございます！

**Comment by mamezou10** [comment]
通りました！
原因は不明なままですが、時間薬ということで。。
ありがとうございます

**Comment by yyoshiaki** [comment]
Nice!
