### ISSUE TITLE
PEでtrimmomaticがとまります→コメントアウトの場所が問題かも

### ISSUE THREAD

**Issue by mamezou10** [yyoshiaki/auto_counttable_maker#9]
https://github.com/yyoshiaki/auto_counttable_maker/blob/master/MakeCountTable_Illumina_SRR.sh#L247

**Comment by yyoshiaki** [comment]
fork -> PRまでおねがいします！

**Comment by yyoshiaki** [comment]
https://github.com/yyoshiaki/auto_counttable_maker/commit/4f1ab9f11f99713db34ede77ebcbf46702425c2a
